# Generated by Django 4.2 on 2023-05-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='perfil',
        ),
        migrations.AddField(
            model_name='empleado',
            name='perfiles',
            field=models.ManyToManyField(to='core.perfil', verbose_name='Perfiles'),
        ),
    ]
