# Generated by Django 4.2 on 2023-05-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_perfil_options_remove_producto_proveedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='producto',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='productos',
            field=models.ManyToManyField(to='core.producto', verbose_name='Productos'),
        ),
    ]
