# Generated by Django 4.2 on 2023-05-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_detalleventa_producto_detalleventa_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_venta',
            field=models.IntegerField(default=1, unique=True, verbose_name='Número de venta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
